### ISSUE TITLE
Another Page like Writting

### ISSUE THREAD

**Issue by STnetwork** [probberechts/cactus-dark#29]
Hi,

Firstly thanks for your theme, I want to create a page like the page Writting, where it appears automatically article, but with only special tag or categories, not all articles, can you help me please ?

**Comment by probberechts** [comment]
If you include a tag in a blog post, eg:
```
title: Tags
date: 2013-12-24 23:29:53
tags:
- Foo
---
This post contains a tag.
```
Then an archives page corresponding to this tag is created automatically at https://site.com/tags/Foo/.

If this is too simple, maybe this [blog post](https://www.ianrose.me/articles/getting-posts-by-category-with-hexo/) can help you?

Otherwise, the general Hexo repo may be a better place to ask these types of questions. I don't know a lot about the Hexo API.
