### ISSUE TITLE
how to navigate the next article when use cellphone?

### ISSUE THREAD

**Issue by walkerwzy** [probberechts/cactus-dark#30]
in web browser, there is a menu button, and trigger navigation buttons(<, >, ^, share) show or hidden, but when visit in mobile browser, the these buttons has gone away, and there's no way to go to the next/prev article.

besides, I can show only 10 (configured in _config.yaml) articles in every archive page (including home page), and can't find a way to show them all or enable the pagination

**Comment by probberechts** [comment]
I omitted the buttons to navigate to the next/previous article in the mobile version. Space is very limited on mobile screens and I sacrificed these buttons, since they are not essential according to me. However, feel free to change the implementation if you find them important.

Pagination is not implemented. You have to implement it yourself (or wait until I have time to do so) or disable it by setting
```
per_page: 0
```
The home page is no archive page. It is programmed to show only the 5 most recent articles by default. You can change this by setting 
```
customize:
    post_count: 5
```
or again, you can adapt the code.
