### ISSUE TITLE
what are difference between "page.post.sort()" and "site.post.sort()"?

### ISSUE THREAD

**Issue by yizhimanpadewoniu** [probberechts/cactus-dark#32]
I found that why the archive page can't view all my post pages just because the difference between the flowing codes。  

`<% site.posts.sort('date', 'desc').limit(theme.customize.post_count || 5).each(function(post, i){ %>`

and  

`<% page.posts.sort('date', 'desc').each(function(post) { %>`

you can see "page" and "site" at the beginning.

**Comment by probberechts** [comment]
`site.posts` lists all existing posts, while `page.posts` filters these posts based on the current page and uses pagination.  I am using the `page.posts` variable for the archive layout, because this makes it possible to filter the posts on a specific tag, month, ... (eg: https://probberechts.github.io/cactus-dark/tags/example/). If you don't need all this, then I suppose you can change it to `site.posts`, but a better solution is to disable pagination by adding `per_page: 0` to your config.
