### ISSUE TITLE
Sandwich disappears when on mobile

### ISSUE THREAD

**Issue by Biarity** [probberechts/cactus-dark#5]
There's no way to go back home, navigate through posts, or share when on mobile. Maybe keep the sandwich icon?

**Comment by probberechts** [comment]
I am aware of this. I am planning to port the current desktop menu to mobile and tablet screens, but this is not straightforward and I probably won't find the time to do so before next week.

I will keep the sandwich icon on other screen sizes. However, there is no or not enough space left in the margin to use the current format and I will have to adapt it to touch screens.

For now, it is possible to go to the other pages via the footer menu and most browsers have a share button built-in.

**Comment by Biarity** [comment]
I've made a PR for a possible concept of how this may be done, I understand it may not be simplistic enough for this design but I found it useful.

**Comment by apolytos** [comment]
Is it possible to keep the sandwich always enabled while on a page post?

**Comment by apolytos** [comment]
@probberechts Is it possible to keep the menu bar always enabled while on a page post?

**Comment by richja** [comment]
second that, at least on desktop

**Comment by apolytos** [comment]
@richja I got around to customize the js and get my website working as I wanted, basically a dark vue site lol, https://apolytos.github.io/blog/

in the main.js file you should reverse the if else function so that it would check if visible on click n hide the active class. of course you have to add the active class to menu before that so from first it'd be visible, and can be hidden by clicking 🔢

**Comment by apolytos** [comment]
@probberechts could you share the markdown file for this post? https://probberechts.github.io/cactus-dark/2016/11/01/An-overview-of-all-Markdown-elements/

It'd help a lot in understanding the markdown, since I am new to this. Thanks.

**Comment by richja** [comment]
@apolytos thank you, looks promising!

**Comment by probberechts** [comment]
@apolytos Personally, I don't like your adaption. For the post page I want to focus on the content and hide as much clutter as possible. But feel free to adapt the theme to your preference 😃.

**Comment by probberechts** [comment]
@apolytos You can download the source of the markdown post [here](https://dl.dropboxusercontent.com/u/46352089/An-overview-of-all-Markdown-elements.md).

**Comment by apolytos** [comment]
@probberechts yes it'd seem cluttered, I'd try to modify the code so that when we click the button the toc & share button are visible. But I want the navigation buttons, to top button always visible. CUrrently I don't have a toc, but yes with a post legend on right side always it'd be kinda cluttered.

**Comment by apolytos** [comment]
![image](https://cloud.githubusercontent.com/assets/22069968/20813886/6f334940-b83d-11e6-8747-c00ae51f70c8.png)

when you click the menu icon, the toc appears , and I've replaced most colors with the color accent i.e green. will upload the files to the repository I made by forking this repo.
