### ISSUE TITLE
All blank lines are removed from the code

### ISSUE THREAD

**Issue by lxw0109** [probberechts/cactus-dark#64]
All blank lines in my code are removed. For example, the blank lines in every code block in [this article](http://xiaoweiliu.cn/2017/10/06/Durable-Redis-pubsub/) are removed, however the same file on [github](https://github.com/lxw0109/lxwBlog/blob/master/source/_posts/Durable-Redis-pubsub.md) is rendered correctly.

How to keep the blank lines in the code?  
Thank you~

**Comment by probberechts** [comment]
This should have been fixed in https://github.com/probberechts/cactus-dark/commit/a2c6550f13a90e7e2203fa9384145f78ca7d27ab. Are you sure that you have the most recent version? Blank lines are displayed correctly in [this example post](https://probberechts.github.io/cactus-dark/2013/12/25/tag-plugins/) in my browser.

**Comment by lxw0109** [comment]
Hi, @probberechts Thank you for your help. It works now ([this article](http://xiaoweiliu.cn/2017/10/06/Durable-Redis-pubsub/)).  
I'm using an old version before Apr 2017.  
Sorry for bothering.   : P
